# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: corosteg <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/05/20 18:06:30 by corosteg          #+#    #+#              #
#    Updated: 2019/05/20 18:06:35 by corosteg         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME: contact
SRC: Contact.class.cpp contact.cpp
CC: g++
FLAGS: -Wall -Wextra -Werror

all: $(NAME)

$(NAME): cc $(FLAGS) $(SRC) -o $(NAME)